export enum EscolaridadeEnum{
    ANALFABETO = 'ANALFABETO', 
    FUNDAMENTAL_COMPLETO = 'FUNDAMENTAL_COMPLETO',
    MEDIO_INCOMPLETO = 'MEDIO_INCOMPLETO',
    MEDIO_COMPLETO = 'MEDIO_COMPLETO',
    SUPERIOR_INCOMPLETO = 'SUPERIOR_INCOMPLETO',
    SUPERIOR_COMPLETO = 'SUPERIOR_COMPLETO',
    MESTRADO = 'MESTRADO',
    DOUTORADO = 'DOUTORADO',
    IGNORADO = 'DOUTORADO'
}